import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReactQueryProvider } from '@/lib/react-query-provider';
import { Toaster } from 'react-hot-toast';
import Navbar from '@/features/dashboard/Page/components/Navbar';
import Breadcrumb from '@/features/dashboard/Page/components/Breadcrumb';
import Footer from '@/features/dashboard/Page/components/Footer';
import FixedLoginButton from '@/features/dashboard/Page/components/FixedLoginButton';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReactQueryProvider>
          <Navbar />
          <Breadcrumb />
          {children}
        </ReactQueryProvider>
        <Footer />
        <FixedLoginButton />
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
